# Generated by Django 5.0.8 on 2024-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_remove_asset_image_assetimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
