# Generated by Django 5.0.8 on 2024-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_remove_assetimage_caption_asset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
        migrations.AddField(
            model_name='assetimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
