# Generated by Django 5.0.8 on 2024-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_remove_asset_image_assetimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
    ]
